import type { Metadata } from "next";
import "./globals.css";
import ChildLayout from "./childLayout";

export const metadata: Metadata = {
  title: "Edu Laibary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className='flex flex-col min-h-screen'>
        <ChildLayout>
          {children}
        </ChildLayout>
      </body>
    </html>
  );
}
