import type { Metadata } from "next";
import "./globals.css";
import ChildLayout from "./childLayout";

export const metadata: Metadata = {
  title: "Edu Laibary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ChildLayout>
          {children}
        </ChildLayout>
      </body>
    </html>
  );
}
